version: "3"

volumes:
  wordpress_volume:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/wboutzou/data/wordpress
  mariadb_volume:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/wboutzou/data/mariadb

networks: 
  inception:
    driver: bridge

services: 
  mariadb:
    container_name: mariadb
    build: 
      context: ./requirements/mariadb
      args:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
    restart: always
    volumes:
      - mariadb_volume:/var/lib/mysql/
    env_file: 
      - .env 
    networks:
      - inception 
    init : true

  wordpress:
    container_name: wordpress 
    build: ./requirements/wordpress 
    volumes:
      - wordpress_volume:/var/www/html/wordpress 
    env_file:
      - .env 
    networks:
      - inception 
    depends_on: 
      - mariadb
    restart: always
    init : true 

  nginx:
    container_name: nginx
    depends_on: 
      - wordpress
    build: ./requirements/nginx/
    networks:
      - inception 
    ports:
      - 443:443 
    env_file:
      - .env
    volumes:
      - wordpress_volume:/var/www/html/wordpress 
    restart: always
    init : true
