version: "3"
volumes:
  wordpress_volume:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ./volumes/wordpress
  mariadb_volume:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ./volumes/mariadb

networks: 
  mynetwork:
    driver: bridge

services: 
  mariadb:
    container_name: mariadb
    build: ./srcs/mariadb
    restart: always
    environment:
      - MYSQL_ROOT_PASSWOR=${MYSQL_ROOT_PASSWORD} 
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
    volumes:
      - mariadb_volume:/var/lib/mysql/
    env_file: 
      - .env 
    networks:
      - mynetwork 
    init : true

  wordpress:
    container_name: wordpress 
    build: ./srcs/wordpress 
    volumes:
      - wordpress_volume:/var/www/html/wordpress 
    env_file:
      - .env 
    networks:
      - mynetwork 
    depends_on: 
      - mariadb
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - WORDPRESS_DB_HOST=${WORDPRESS_DB_HOST}
      - WORDPRESS_DB_NAME=${WORDPRESS_DB_NAME}
      - WORDPRESS_DB_PASSWORD=${WORDPRESS_DB_PASSWORD} 
      - WORDPRESS_TABLE_PREFIX=${WORDPRESS_TABLE_PREFIX}
    restart: always
    init : true 

  nginx:
    container_name: nginx
    depends_on: 
      - wordpress
    build: ./srcs/nginx/
    networks:
      - mynetwork 
    ports:
      - 443:443 
    env_file:
      - .env
    volumes:
      - wordpress_volume:/var/www/html/wordpress 
    restart: always
    init : true
